import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { resolve } from 'node:path'
import type { Plugin } from 'vite'

type SimpleIcon = { slug: string; title: string; hex: string; path: string }
type AppEntry = { name: string; slug: string | null; policyApp?: string }
export type LogoInfo =
  | { source: 'simple-icons'; title: string; hex: string; path: string }
  | { source: 'file'; src: string }

const VIRTUAL_ID = 'virtual:logos'
const RESOLVED_ID = '\0' + VIRTUAL_ID

/**
 * Resolves every app logo at build time:
 * 1. public/logos/{app}.svg|png|webp (official files added by hand win)
 * 2. Simple Icons (only if the slug exists in the installed version)
 * 3. nothing -> the UI shows a name tile
 * Exposes the result as `virtual:logos` and writes LOGOS.md.
 */
export function logosPlugin(root: string): Plugin {
  const configPath = resolve(root, 'apps.config.json')

  function build() {
    const require = createRequire(import.meta.url)
    const si = require('simple-icons') as Record<string, SimpleIcon>
    const bySlug = new Map<string, SimpleIcon>()
    for (const icon of Object.values(si)) if (icon?.slug) bySlug.set(icon.slug, icon)
    const pkgPath = resolve(root, 'node_modules/simple-icons/package.json')
    const version = (JSON.parse(readFileSync(pkgPath, 'utf8')) as { version: string }).version

    const { apps } = JSON.parse(readFileSync(configPath, 'utf8')) as { apps: Record<string, AppEntry> }
    const logos: Record<string, LogoInfo> = {}
    const names: Record<string, string> = {}
    const policyApp: Record<string, string> = {}
    const rows: string[] = []

    for (const [id, entry] of Object.entries(apps)) {
      names[id] = entry.name
      if (entry.policyApp) policyApp[id] = entry.policyApp
      const alias = entry.policyApp ? ` (asks as \`${entry.policyApp}\`)` : ''
      const icon = entry.slug ? bySlug.get(entry.slug) : undefined
      const ext = ['svg', 'png', 'webp'].find((e) => existsSync(resolve(root, 'public/logos', `${id}.${e}`)))
      if (ext) {
        logos[id] = { source: 'file', src: `logos/${id}.${ext}` }
        rows.push(`| ${id}${alias} | ${entry.name} | \`public/logos/${id}.${ext}\` (added by hand) |`)
      } else if (icon) {
        logos[id] = { source: 'simple-icons', title: icon.title, hex: icon.hex, path: icon.path }
        rows.push(`| ${id}${alias} | ${entry.name} | Simple Icons (\`${icon.slug}\`, #${icon.hex}) |`)
      } else {
        rows.push(`| ${id}${alias} | ${entry.name} | Name tile (not in Simple Icons ${version}, no file in \`public/logos/\`) |`)
      }
    }

    const md = [
      '# Logos',
      '',
      `Generated by \`scripts/logos-plugin.ts\` on every dev start and build. Checked against simple-icons ${version}.`,
      '',
      'Order of sources: `public/logos/{app}.svg|png|webp` (official files added by hand), then Simple Icons, then a rounded tile with the display name.',
      'Gmail and YouTube are shown separately but use Google\'s policies (`policyApp: google`).',
      'Logos are never drawn or redrawn by hand. Logos belong to their owners.',
      '',
      '| App id | Name | Source |',
      '| --- | --- | --- |',
      ...rows,
      '',
    ].join('\n')
    const mdPath = resolve(root, 'LOGOS.md')
    if (!existsSync(mdPath) || readFileSync(mdPath, 'utf8') !== md) writeFileSync(mdPath, md)

    return `export const logos = ${JSON.stringify(logos)};\nexport const fallbackNames = ${JSON.stringify(names)};\nexport const policyApp = ${JSON.stringify(policyApp)};\n`
  }

  return {
    name: 'policy-translator-logos',
    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID
    },
    load(id) {
      if (id === RESOLVED_ID) {
        this.addWatchFile(configPath)
        return build()
      }
    },
  }
}
